[package]
name = "kv-cache"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme = "README.md"

[dependencies]
candle-core = "0.9.1"